{% set name = "distinctipy" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/distinctipy-{{ version }}.tar.gz
  sha256: 726d0a018134211575783c7392083e6e20c3388b1ce04e8c3495e346f986112f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.16.3

test:
  imports:
    - distinctipy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alan-turing-institute/distinctipy
  summary: A lightweight package for generating visually distinct colours.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
