{% set name = "distinctipy" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/distinctipy-{{ version }}.tar.gz
  sha256: 9dd121cfa29f3d1dc491316edfed093e5eea10504aa52174d439e053a11a58fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.16.3

test:
  imports:
    - distinctipy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alan-turing-institute/distinctipy
  summary: A lightweight package for generating visually distinct colours.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
